### ISSUE TITLE
Public release: 1.0.0-BETA

### ISSUE THREAD

**Issue by AlteOgre** [VulcanForge/pvp-mode#21]
So ... how close are we to release public beta v1.0? What is the exact current status of the mod / needs to be completed for that release?
As discussed almost a month ago, VF would strive to launch the publuc beta v1.0 after completing a few bug fixes and implementing the combat logging. We're very close to that milestone. Remaining bugs are fixed with test confirmation.
Is the combat logging feature fit to unleash it to servers or does it need a few more improvements first? Was testing sufficient yet, or do we need a few more specific tests? How does it match Maht's teleport blocker? Think combat initiation trigger and duration timer. We could settle for a rough default for v1.0 and tune it in next version(s)?
There have been a few additional improvements in the meantime, which are those exactly? Just a brief reminder of them and I will check them out and add to the LOTRmod wiki page / GitHib wiki, if needed. I recall improved pvphelp, pvpconfig addition, blocking of teleports after combat initiaition ... anything else?

As Mevans still hasn't responded to our request for endorsement, I cannot create a dedicated wiki page yet, so I will create a new thread in the News & Announcements Board, as approved by my wiki staff colleagues and just like CM did for his NEI Addon. I 'only' need confirmation of v1.0 completion: make it the new master (incl. updated readme etc.).

Let's work on that now before continuing on any other (announced) additions.

#### Todo (before official release):
- [x] Finish all issues in the milestone
- [x]  Apply the formatting settings to all files
- [x] Update `README.md`
- [x] Update the changelog
- [x] Declare the version as feature complete
- [x] Release a test version (1.0.0-BETA.n for the n-th pre-release) 
- [x] Every issue reported by the testers will be fixed (and a new pre-release released)
- [x] Declare the version as complete
- [x] Merge `development` with `master`
- [x] Create a github release containing the .jar
- [x] Update the wiki
- [x] Launch a new thread in the News&Announcements board of the LOTRmod wikia for future exchange with our user/client base

#### Changelog:
* Added combat logging (two handlers: `csv` (default) and `simple`). The logs files are stored under `logs/combat` and will be changed every server start.
* Java 8 is now required (important for Servers!)
* Some performance improvements and an internal cleanup
* Fixed that typing invalid player names in `pvpadmin` outputs an unmeaningful error message
* Improved `pvphelp` (added a header and clickable commands which will be inserted in the chat). Also it won't display configuration data anymore.
* Removed `pvpcancel`. Canceling now will be done via `pvp cancel`
* Added a command `pvpconfig` which displays the configuration data. Only accessible for operators with at least level 2.
* The default distance rounding factor for the player radar is now 100 instead of 64

**Comment by CraftedMods** [comment]
I think we can release Beta 1.0 if the combat logging PR was merged.
Some new featured/improvements of Beta 1.0 are:
* Java 8 is now required (important for Servers!)
* Some performance improvements and internal cleanup
* Fixed that typing invalid player names in `/pvpadmin` outputs an unmeaningful error message
* Improved `pvphelp`
* Added pvp combat logging with two handler: default and csv
I think the improvements related to combat logging should be released with a new version. Otherwise we'll work forever on Beta 1.0. 
Currently, there's no PR for the `pvpconfig` command. I'm currently working on this feature, but it requires some of the current PR's to be merged.
@AlteOgre I think it would make sence if you have the main responsibility for creating issues for planned features and assigning them to milestones for future versions.

**Comment by CraftedMods** [comment]
Should we release a pre-release version for testing purposes? It would be `1.0.0-BETA.1`. Or should we release `1.0.0-BETA` directly? What do you think?

**Comment by AlteOgre** [comment]
Which aspects are still to be tested?
If there is some uncertainty about feature behaviour in proper servers, I'd go for the pre-release and distribute it to a few server owners: Veliks and MilkMC are best targets imo.

**Comment by CraftedMods** [comment]
We should test everything. The highest risk in my opinion is that something did break with the last changes. Also some testing related to performance would be nice - so we would know how high the priority for performance related fixes is. Currently the're assigned to `1.1.0-BETA`, but if performance suffers notifeable, we have to move this to `1.0.0-BETA`.

**Comment by CraftedMods** [comment]
If @Mahtaran reviewed the last two remaining PRs from me and I created a PR for the `pvpconfig` command (with only display support), I would suggest that we won't work on new features for this release but release some pre-releases for testing purposes. If the tests work fine, we'll release `1.0.0-BETA` and merge `development` with `master`.

**Comment by CraftedMods** [comment]
@AlteOgre Could you post your thoughts about #26 ? If we change it, we should change it as soon as possible.

**Comment by AlteOgre** [comment]
Okay, so we should test it all again with latest version. Do note that I believe we won't get any significant performance test results unless we can test it on a major server. We could ask Veliks and Milk to run the test version on their servers. They both have peak attendances of 10+ players daily. Poke me when the test version is ready and when you agree to approach Veliks and Milk. Then I'll forward our request and do some tests on my local lan server as well.

**Comment by CraftedMods** [comment]
I've added a proposed changelog and a todo list for the next release to the first post.

**Comment by CraftedMods** [comment]
Also, for the next release, we should create a Github Project for it (an not an issue).

**Comment by CraftedMods** [comment]
All issues in the milestone `1.0.0-BETA` were closed. I'll create a PR with the formattings.

**Comment by CraftedMods** [comment]
Merged #36. The milestone remains open, because of bugs which may occurr with the tests.

**Comment by AlteOgre** [comment]
I sense all the necessary mergers may have been executed by now. Which is the jar that can be used for testing?

**Comment by CraftedMods** [comment]
I'll build it later and provide a link to it. Could you meanwhile look over the readme file in the branch `development` and check (and if necessary expand) it? For this you don't have to create a PR but can edit it directly in the branch `development`.

**Comment by CraftedMods** [comment]
Also, I updated the changelog with 11df48de6fb3010d5c91897c3745d33715bc97d9.

**Comment by CraftedMods** [comment]
I built `1.0.0-BETA.1` and added it to `development` (with #37 ). We'll create a Github release for the first full version, `1.0.0-BETA`. The `development` branch contains the pre-release.

**Comment by CraftedMods** [comment]
Download: https://github.com/VulcanForge/pvp-mode/raw/development/pvp-mode-1.0.0-BETA.1.jar
@AlteOgre Please distribute it to our testers. Everything what they do report (especially bugs) should be opened with a new issue which will be assgned to the milestone `1.0.0-BETA` - unless we thing that this really is something for the next versions.

**Comment by AlteOgre** [comment]
Okay. Thanks! I'll be available for this in next few days, starting now. Both Veliks and Milk have indicated they are willing to test it. I will do some LAN server checks to rule out major bugs before I further distribute it.

**Comment by AlteOgre** [comment]
Tested in LAN with Grumpy and me + each one hired unit. I think I tested all possible scenarios. All functioned properly. So I'll forward the test version to Veliks and Milk asap (within a hour, after some household things).

One remarkable aspect for later concern: If a player with PvP Mode ON attacks a player with PvP Mode OFF, or his hired units, and this triggers a hired unit to attack as well, the hired unit will remain attacking without causing any damage. That looks silly but can be very annoying as well. Something to tackle in a future update.

**Comment by CraftedMods** [comment]
Please open an issue for this.

**Comment by CraftedMods** [comment]
The permission nodes are based on the command names and the modid, are they?

**Comment by AlteOgre** [comment]
If I understand it correctly, those nodes are directly derived from the class files that define / are referred to by commands.

**Comment by AlteOgre** [comment]
Forge documentation may likely provide clearer evidence for this. After all, all plugin and mod developers using permissions (which are a great deal of them), should be informed properly about how Forge assigns/defines permission nodes.

**Comment by CraftedMods** [comment]
I think permission nodes were added by `Forge Essentials`. I've never heard from permission nodes from `Minecraft Forge`. `Forge Essentials` creates a file with the permission nodes of all registered commands. Do you have such a file (or can the testers provide a such one)? It should be something like `PermissionList.txt`.

**Comment by AlteOgre** [comment]
In that case plugins like Pex and GM could act in a similar manner. Yet, I cannot find any such file ever created by Pex on my old 1.7.10 servers. So it seems to work a little differently as both you and me assumed. I think the list of permissions created by FE can be considered a user friendly service. FE derives them from the file structure for the users. Users do have to type in all permissions they wish to assign in a config file anyway. Pex and GM work in a similar manner, with and without Forge. Maybe it's Spigot that controls this, or the permissions mods/plugins themselves ofc. Better no more speculating (I tend tod o that a lot), and dive into the code of things?

**Comment by CraftedMods** [comment]
This was no speculation. I actually read about it (https://github.com/ForgeEssentials/ForgeEssentials/wiki/Permissions-tutorial). Also I assumed that currently we only talk about`Forge Essentials`. I don't think that we really have to know how these plugins work - as we see it seems that the permission node names were generated based on the filename for `Forge Essentials`, but other plugins may do this with other methods. So the only important thing regarding this is that we shouldn't change the command names and command file names unless really necessary.

**Comment by AlteOgre** [comment]
I saw that too and wasn't suggesting you were speculating. I wasn't merely talking about FE as there are many servers not using that but instead using a KCauldron fork and either Pex or GM for permission management. And yes, no command changes unless much needed and unavoidable. As we only had a few servers running the pre-BETA, I felt the changes we made in past month would be no big issue.

**Comment by CraftedMods** [comment]
Do you know how much servers are running this mod? And how much servers are interested in using it?

**Comment by AlteOgre** [comment]
Currently three use it. At one point in past months there were 9 server owners who showed serious interest.

**Comment by AlteOgre** [comment]
On a sidenote: CM, did you just join the wiki discord as Malvegil#1928?

**Comment by CraftedMods** [comment]
Yes, I did. But I'll only be there sometimes to look for news and so on, so don't expect that I'll be very active in there.

**Comment by AlteOgre** [comment]
I somehow had expected Maht to have implemented the blocking of teleportation after combat was initiated, but it seems that is not the case. What is the status of that feature? It was mostly discussed in the Fb chat. If not implemented, I will open a seperate issue on it.

**Comment by Mahtaran** [comment]
Yeah sorry, I’ve been reall busy with exams. I’ll try to implement it as soon as possible, but I’ve got no clue when that is.

**Comment by CraftedMods** [comment]
Any feedback from our testers so far?

**Comment by AlteOgre** [comment]
No oddities or malfunctions reported so far. Both Veliks and MilkMC have implemented the new version on their servers.

**Comment by CraftedMods** [comment]
Nice. Could you ask them to look how the performance with pvp logging enabled is (I'm thinking about #42). Some input regarding this would be nice, so we can correctly priorize this issue.

**Comment by CraftedMods** [comment]
Just say if you think that we can finish the testing phase and release the first version.

**Comment by CraftedMods** [comment]
Are our testers still testing? Two weeks seem very long for such a small mod like this.

**Comment by AlteOgre** [comment]
We can consider the  version ready for master. I asked for feedback several times and observed the experiences in-game. No complaints/bugs regarding v1.0.0-BETA. Do make it the new master and declare it complete.
I'll prepare a new wiki thread as discussed, and close the old one, in next few days. Sorry for being less active last weeks, but I had a lot of trouble coping with my abdominal nerve pains, so all productive thinking and action went considerably slower. I mainly just played as a zombie because of that. Nonetheless, I compiled all open issues in one document. Next is to turn them into issues and prioritise them. That will be continued in another thread ofc.

**Comment by CraftedMods** [comment]
I've created the release and uploaded the built (and final) JAR.

**Comment by CraftedMods** [comment]
I just saw that AlteOgre updated the wiki and created a new forum thread in the wiki. Thanks! The work on `1.1.0-BETA` is now officially finished.
